import { ProductCardProps, SortOption } from "@/app/types/product";
import { BannerItem } from "@/app/types/bannerSlider";

export const MOCK_PRODUCTS: ProductCardProps[] = [
  {
    id: 1,
    image: "https://picsum.photos/seed/product1/400/400",
    brand: "까사미아",
    name: "모던 패브릭 2인 소파 그레이 컬러 거실용 미니멀 디자인",
    discountRate: 30,
    price: 189000,
    originalPrice: 270000,
    rating: 4.8,
    reviewCount: 1243,
    isFreeShipping: true,
    badge: "BEST",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/product2/400/400",
    brand: "이케아",
    name: "북유럽 원목 커피 테이블 화이트 오크 거실 인테리어",
    discountRate: 15,
    price: 129000,
    originalPrice: 152000,
    rating: 4.6,
    reviewCount: 874,
    isFreeShipping: true,
    badge: "NEW",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/product3/400/400",
    brand: "한샘",
    name: "슬림 수납 책상 + 의자 세트 홈오피스 재택근무 추천",
    discountRate: 25,
    price: 215000,
    originalPrice: 287000,
    rating: 4.7,
    reviewCount: 532,
    isFreeShipping: false,
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/product4/400/400",
    brand: "무인양품",
    name: "스탠드 조명 화이트 침실 간접조명 심플 디자인",
    discountRate: 20,
    price: 68000,
    originalPrice: 85000,
    rating: 4.5,
    reviewCount: 391,
    isFreeShipping: true,
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/product5/400/400",
    brand: "오늘의집",
    name: "라탄 수납 바구니 대형 욕실 빨래 정리함 인테리어 소품",
    discountRate: 10,
    price: 32000,
    originalPrice: 35000,
    rating: 4.9,
    reviewCount: 2018,
    isFreeShipping: true,
    badge: "BEST",
  },
  {
    id: 6,
    image: "https://picsum.photos/seed/product6/400/400",
    brand: "퍼시스",
    name: "에르고노믹 허리 지지 회전 의자 메쉬 사무용 체어",
    discountRate: 35,
    price: 198000,
    originalPrice: 305000,
    rating: 4.7,
    reviewCount: 765,
    isFreeShipping: true,
  },
  {
    id: 7,
    image: "https://picsum.photos/seed/product7/400/400",
    brand: "까사미아",
    name: "침실 6단 서랍장 오크 우드 화이트 프레임 수납장",
    discountRate: 18,
    price: 245000,
    originalPrice: 299000,
    rating: 4.4,
    reviewCount: 321,
    isFreeShipping: false,
    badge: "NEW",
  },
  {
    id: 8,
    image: "https://picsum.photos/seed/product8/400/400",
    brand: "아로마",
    name: "대형 캔버스 아트 프린트 거실 포스터 인테리어 그림",
    price: 45000,
    rating: 4.3,
    reviewCount: 189,
    isFreeShipping: true,
  },
];

export const PRODUCT_BANNERS: BannerItem[] = [
  {
    id: 1,
    subtitle: "단독 컬렉션",
    title: "ohouse",
    titleBadge: "edition",
    description: "OLLY 컴팩트 모듈 선풍기 쿠폰 할인",
    imageUrl: "https://picsum.photos/seed/banner1/600/400",
    bgColor: "#f0eeeb",
    href: "/product/exclusive",
  },
  {
    id: 2,
    subtitle: "신규 입점",
    title: "여름 특가",
    titleBadge: "SALE",
    description: "에어컨 & 냉방 가전 최대 20% 할인",
    imageUrl: "https://picsum.photos/seed/banner2/600/400",
    bgColor: "#e8f0f8",
    href: "/product/deal",
  },
  {
    id: 3,
    subtitle: "베스트 셀러",
    title: "인테리어",
    titleBadge: "pick",
    description: "이달의 베스트 인테리어 아이템",
    imageUrl: "https://picsum.photos/seed/banner3/600/400",
    bgColor: "#f0f0e8",
    href: "/product/best",
  },
];

export const PRODUCT_SORT_OPTIONS: { label: string; value: SortOption }[] = [
  { label: "추천순", value: "recommended" },
  { label: "신상품순", value: "newest" },
  { label: "낮은가격순", value: "price_asc" },
  { label: "높은가격순", value: "price_desc" },
  { label: "리뷰많은순", value: "review" },
];
